/*
 * VentanaPrincipal.java
 *
 * Created on 29 de junio de 2007, 1:51
 */

package ejercicioswing;

import com.sun.org.apache.bcel.internal.generic.SALOAD;
import javax.swing.JButton;

/**
 *
 * @author  Arturo Gomez del C
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Calculadora cal;
    private boolean primerNumeroOperando;
    private String operacionPendiente;
    
    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        initComponents();   
        this.cal = new Calculadora();
        this.primerNumeroOperando = true;
        this.operacionPendiente = "";
        this.setTitle("Mi calculadora swing");
        this.setSize(257,300);
    }
    
    private int ejecutarOperacionPendiente(int operando){
        int result = 0;
        
        if (this.operacionPendiente.equals("+"))
            result = this.cal.sumar();
        else if (this.operacionPendiente.equals("-"))
            result = this.cal.restar();
        else if (this.operacionPendiente.equals("*"))
            result = this.cal.multiplicar();
        else result = operando;        
        
        return result;        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        botonSiete = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonMult = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        salida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        botonSiete.setText("7");
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonNueve.setText("9");
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonOcho.setText("8");
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonCuatro.setText("4");
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonSeis.setText("6");
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonCinco.setText("5");
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonUno.setText("1");
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonTres.setText("3");
        botonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonDos.setText("2");
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        botonCero.setText("0");
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPulsadoListener(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMult.setText("*");
        botonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperacionActionPerformed(evt);
            }
        });

        jPanel1.add(botonMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, -1));

        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });

        jPanel1.add(botonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 50, -1));

        botonMas.setText("+");
        botonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperacionActionPerformed(evt);
            }
        });

        jPanel1.add(botonMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        botonMenos.setText("-");
        botonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperacionActionPerformed(evt);
            }
        });

        jPanel1.add(botonMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 50, -1));

        salida.setEditable(false);
        salida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        salida.setText("0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, salida, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, botonSiete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, botonUno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(botonDos, 0, 0, Short.MAX_VALUE)
                                    .add(botonCinco, 0, 0, Short.MAX_VALUE)
                                    .add(botonOcho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(botonCuatro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(botonCero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(botonTres, 0, 0, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(botonSeis, 0, 0, Short.MAX_VALUE)
                                .add(botonNueve, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(salida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(61, 61, 61)
                                    .add(botonSeis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(botonNueve, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(80, 80, 80)
                                    .add(botonTres, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(46, 46, 46))
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(61, 61, 61)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(botonCuatro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(botonCinco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(botonSiete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(botonOcho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(80, 80, 80)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(botonUno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(botonDos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(botonCero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(427, 427, 427))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        int operando = Integer.parseInt(this.salida.getText());
        cal.agregarOperando(operando);
        this.salida.setText(""+this.ejecutarOperacionPendiente(operando));
        this.primerNumeroOperando = true;
        this.operacionPendiente = "";
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOperacionActionPerformed
        int operando = Integer.parseInt(this.salida.getText());        
        cal.agregarOperando(operando);
        
        int result = this.ejecutarOperacionPendiente(operando);       
        
        /**Se anota la operacion que se ha pulsado a espera del segundo operando*/
        this.operacionPendiente = ((JButton)evt.getSource()).getText();
        this.salida.setText(""+result);
        
        this.primerNumeroOperando = true;
    }//GEN-LAST:event_botonOperacionActionPerformed

    private void botonPulsadoListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPulsadoListener
        /**Se obtiene el boton en donde ha ocurrido el evento*/  
        JButton botonPulsado = (JButton)evt.getSource();
        
        /**Se extrae el numero que se ha pulsado*/
        String numeroPulsado = botonPulsado.getText();
        
        String resultado = "";
        
        if (this.primerNumeroOperando){
            resultado = numeroPulsado;
            this.primerNumeroOperando = false;
        }else 
            resultado = this.salida.getText()+numeroPulsado;
        
        /**Se a�ade en el display de salida*/
        this.salida.setText(resultado);        
    }//GEN-LAST:event_botonPulsadoListener
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonMult;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonTres;
    private javax.swing.JButton botonUno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField salida;
    // End of variables declaration//GEN-END:variables
    
}
